### ISSUE TITLE
create-snowpack-app-react breaks after reinstall

### ISSUE THREAD

**Issue by matthoffner** [pikapkg/create-snowpack-app#85] opened 2020-05-28 20:40 UTC
Steps to reproduce:

```
npx create-snowpack-app new-project --template @snowpack/app-template-react
cd new-project
npm run start
```

Then I removed node modules and lock file

```
rm -rf node_modules && rm package-lock.json
npm install
npm run start
```

Then I get this error, and things are broken:
```
Error: Parse error @:11:60
 at Object.parse
    at getInstallTargetsForFile 
    at Array.map (<anonymous>)
    at scanImports 
    at async command 
    at async command 
```

**Comment by FredKSchott** [comment] 2020-05-28 22:38
Not good! Thanks for filing. This is a duplicate of https://github.com/pikapkg/snowpack/issues/369, would love your help fixing if you're interested in submitting a PR.

**Closed by FredKSchott** 2020-05-28 22:38 UTC
