### ISSUE TITLE
React Typescript Template Fails

### ISSUE THREAD

**Issue by iBaldie** [pikapkg/create-snowpack-app#10] opened 2020-05-06 10:18 UTC
NPM Ignore is ignoring the web-modules folder and causes `npm start` and `npm build` to fail with these errors:
```
Error: Cannot find module '/snowpack-react/web_modules/import-map.json'
Require stack:
- /snowpack-react/node_modules/snowpack/dist-node/index.js
- /snowpack-react/node_modules/snowpack/dist-node/index.bin.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at command$1 (/snowpack-react/node_modules/snowpack/dist-node/index.js:941:31)
    at cli (/snowpack-react/node_modules/snowpack/dist-node/index.js:3026:11)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `snowpack dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by iBaldie** [comment] 2020-05-06 10:19
Could be the .npmignore includes the web-modules folder.....?

**Comment by FredKSchott** [comment] 2020-05-06 16:57
Duplicate of #11, I think. But I'll make sure to test this exact flow before cutting the next release

**Comment by FredKSchott** [comment] 2020-05-06 16:59
Thanks for filing, and sorry for the early release bugs!

**Closed** 2020-05-06 16:59 UTC

**Comment by iBaldie** [comment] 2020-05-06 20:11
Looking forward to using this! 👍

**Comment by iBaldie** [comment] 2020-05-06 20:28
@FredKSchott Its working but the create react typescript boilerplate seems broken, it loads a white page and the public html that gets served is not linked to the react app.... is this intentional? Am I missing something?

**Comment by FredKSchott** [comment] 2020-05-06 20:37
There was a jsx -> tsx typo that just got fixed, is that what you're referring to?

**Comment by iBaldie** [comment] 2020-05-06 20:38
Yes sorry, all fixed now in the latest commit! ☺️
