### ISSUE TITLE
On template-blank : snowpack build --bundle, parcelRequire unknown

### ISSUE THREAD

**Issue by Akanoa** [pikapkg/create-snowpack-app#15] opened 2020-05-06 17:59 UTC
Hello,

Steps to reproduce:

In a fresh folder.

```
yarn add -D snowpack@next
```
`snowpack@2.0.0-beta.6` installed

```
npx create-snowpack-app my-project-blank --template @snowpack/app-template-blank --use-yarn
```
```
npx snowpack build --bundle
```

```
cd build && npx http-server
```
Confetti pop on the screen but there is an error into the dev console:

<img width="665" alt="Capture d’écran 2020-05-06 à 19 56 51" src="https://user-images.githubusercontent.com/4521637/81211515-c7bac900-8fd3-11ea-9b26-49e17156c290.png">

Thanks,

Env: mac mojave | node v11.15.0

**Comment by FredKSchott** [comment] 2020-05-06 18:49
Thanks for filing, i can confirm this is a bug, although the code seems to run just fine.

It looks like Parcel v1 has some bugs when used with type="module" which is causing that reference error. We can point to Parcel v2, which is still in beta but because we're using such a basic setup for Parcel I think that would be more than fine, stability-wise. 

Lets think a bit more about this, but that's where I'm leaning at the moment.

**Comment by FredKSchott** [comment] 2020-05-10 06:42
Solved by moving to parcel v2 (based on convo with parcel maintainer who said Parcel 2 was fairly stable for our zero-plugin usecase). Upgrade to the latest snowpack / csa to enable.

**Closed by FredKSchott** 2020-05-10 06:42 UTC
